name: Release mosdns docker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 28 * *'

jobs:
  deploy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image antonyitunamaku88/mosdns1:latest -a dnsfamily --remote-only --no-cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
