name: Release mosdns docker

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '15 19 * * *'

jobs:
  build-docker:
    name: Deploy proxy
    runs-on: ubuntu-latest
    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --detach -a dnsfamily --remote-only --no-cache && flyctl regions set sin -a dnsfamily
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          
